// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYYYSp_Lih6BKg-6GtJ2ggBe_35nvtD0Q',
    appId: '1:427811452112:web:2a0dca2db83aa213ae1ad5',
    messagingSenderId: '427811452112',
    projectId: 'lciapp-add9e',
    authDomain: 'lciapp-add9e.firebaseapp.com',
    databaseURL: 'https://lciapp-add9e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lciapp-add9e.appspot.com',
    measurementId: 'G-0146E3CNM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC17bVxtPuqDTA1kMtM1IydK0EVN5snSE',
    appId: '1:427811452112:android:f977212fc58e60b5ae1ad5',
    messagingSenderId: '427811452112',
    projectId: 'lciapp-add9e',
    databaseURL: 'https://lciapp-add9e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lciapp-add9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw0tfvsgHFunKhgs_53j9ig3FwHcCamHc',
    appId: '1:427811452112:ios:9475352985873636ae1ad5',
    messagingSenderId: '427811452112',
    projectId: 'lciapp-add9e',
    databaseURL: 'https://lciapp-add9e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lciapp-add9e.appspot.com',
    iosClientId: '427811452112-noq4v29ok6rk6t16lgbcft8jrbroqpqm.apps.googleusercontent.com',
    iosBundleId: 'com.lci.lciProject',
  );
}
